### ISSUE TITLE
Its a typo in the documentation, what is the correct one?

### ISSUE THREAD

**Issue by PetterRuud** [GroupePSA/groupepsa.github.io#36]
1.
Its a typo in the documentation
https://developer.groupe-psa.io/webapi/b2c/connect/#2-access-token
In the example request it says
  --header 'Authorization: Basic <(user:password)base64>' \
but in the schema it is
Header authorization Basic <client_id:client_secret> Indicate that
authentication is Basic Auth and <BASIC_AUTH> is
client_id:client_secret of your application encoded Base64

What is correct?

2. On https://developer.groupe-psa.io/ it says to go to
https://developer.groupe-psa.io/ and subscribe to Connected Car - B2C.
That API does not exist. Only one I can find that is remotely close is
Connected Car Development 1.0.5. And there is this
https://developer-preprod.groupe-psa.com/inc/node/1120
So where can i find the right API to subscribe to?

Thanks in advance

**Comment by NoeReboul** [comment]
Hi, 

thanks for the issue. This is now fixed in the documentation. You should use Header authorization Basic <client_id:client_secret>

**Comment by jordivantuil** [comment]
Doesn't work either. They lack in professionality providing workable documentation.
Above URL returns a 404 when trying to authenticate.
