### ISSUE TITLE
Developer Access to connected car API

### ISSUE THREAD

**Issue by SamuelBrucksch** [GroupePSA/groupepsa.github.io#41]
Hi,

i contacted connectedcar@mpsa.com a week ago but did not get a reply yet. Is this still a valid mail address? I want to to get access to the connected car API to implement a binding for [openhab](https://www.openhab.org/) Smart Home Automation. Can you please guide me how to get access?

BR
Samuel

**Comment by NoeReboul** [comment]
Hi,

thank you for your message. For the moment the API is not publicly available. Sorry for the inconvenience.

Regards,
Noé.

**Comment by SamuelBrucksch** [comment]
Thanks for Your answer. Is there an estimation when it will be available for end users? Will there be a beta phase that one can join for testing?

**Comment by NoeReboul** [comment]
Hi, 

Unfortunately, I have no information regarding the opening date of the APIs. This information will be available on the website when the service opens.

Regards, 
Noé

**Comment by col-panic** [comment]
Also waiting for this for some months now - whats the status on this? Info would be really nice!
