### ISSUE TITLE
Two syntax errors in WebSite examples

### ISSUE THREAD

**Issue by arndl** [GroupePSA/groupepsa.github.io#59]
There are two syntax errors in the examples on WebSite:
https://developer.groupe-psa.io/webapi/b2c/quickstart/connect

1.: There is a "&" missing between parameters "username" and "scope":
https://developer.groupe-psa.io/webapi/b2c/quickstart/connect/#2-access-token

2.: The last backslash is in wrong line. It should be in the third line.
https://developer.groupe-psa.io/webapi/b2c/quickstart/connect/#3-connection-example

**Comment by etiennerobaglia** [comment]
Resolved in PR #60

**Comment by arndl** [comment]
Hopefully this API will be released soon!
