### ISSUE TITLE
Getting a 404 on the Auth endpoints

### ISSUE THREAD

**Issue by hemang249** [GroupePSA/groupepsa.github.io#61]
I'm not sure if this is the correct place to post an issue with api itself but I tried using the Consumer api and I am getting a 404. I have registered the app and obtained my keys.

The endpoint in quesion is this -> **https://idpcvs.{brand.tld}/am/oauth2/access_token**

**Comment by SamuelBrucksch** [comment]
You need to replace brand.tld and the brackets with the manufacturer name like Opel. Also the API is not available yet, so I guess your credentials won't work with it.

**Comment by NoeReboul** [comment]
Hello, the B2C API is not public for the moment. I fully understand your request. We're working on it but I can't give you a schedule.
