### ISSUE TITLE
Is PSA for developers dead?

### ISSUE THREAD

**Issue by SamuelBrucksch** [GroupePSA/groupepsa.github.io#86]
I've been monitoring the docu for quite a while now. I already did some contributions with minor fixes of texts and check back regularily to see if any updates come in. My last interaction here was last year september, so almost one year ago and i've been watching this from much earlier on. In the meantime i already tried to reach out to the contact mail that has been provided, but never got a reply. My last approach via issues was also not really successful (https://github.com/GroupePSA/groupepsa.github.io/issues/41).

So my question is will this ever be available for public use? Is there any timeline when this will be available? Is it possible to get access to an early version for internal testing?

I actually want to use it not for a private project, but for a bigger project related to navigation for EVs. Unfortunately i never got a reply so i will just try it again here. Is it possible to get access to data as a company if it is not available for private use yet?

**Comment by col-panic** [comment]
I second this question!

**Comment by NoeReboul** [comment]
Hello, the B2C API is not public for the moment. There is a B2B access, please fill the contact form available in the website. I fully understand your request for B2C access. We're working on it but I can't give you a schedule.

**Comment by SamuelBrucksch** [comment]
@NoeReboul i already tried to get in touch multiple times but never got a reply. Could you please provide me a mail that i can use to get in contact where i will definitely get a reply?

**Comment by col-panic** [comment]
Same here, both trying to contact B2C and provide bug reports for the iphone app - just a waste of time. Never an answer. I like the car, but the software and the iphone app is so buggy and lacks features, it hurts. 👎

**Comment by sircuri** [comment]
Almost 15 months further and the website still tells that it's not yet open to the public. Some estimations would be real great.
